# Generated by Django 2.2.13 on 2020-06-21 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitas_granada', '0002_visita_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visita',
            old_name='descripción',
            new_name='descripcion',
        ),
    ]
